In [6]:
pip install torch==2.0.0 torchvision==0.15.1

Note: you may need to restart the kernel to use updated packages.


In [7]:
pip install d2l==1.0.3

Note: you may need to restart the kernel to use updated packages.Collecting d2l==1.0.3
     ---------------------------------------- 0.0/59.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/59.0 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 59.0/59.0 kB 616.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/111.7 kB ? eta -:--:--
   ------------------------- -------------- 71.7/111.7 kB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 102.4/111.7 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 111.7/111.7 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/7.5 MB 1.7 MB/s eta 0:00:05
    --------------------------------------- 0.1/7.5 MB 1.6 MB/s eta 0:00:05
    --------------------------------------- 0.2/7.5 MB 1.4 MB/s eta 0:00:06
   - -------------------------------------- 0.2/7.5 MB 1.2 MB/s eta 0:00:0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.


In [2]:
import pandas as pd

data = pd.read_csv('METLIN_CCS_vectorfingerprintsVectorized.csv', nrows = 50)
print(data)

                                        Molecule Name Molecular Formula  \
0   3-[3-(2,3-dihydroindol-1-yl)propyl]-1-[(4-fluo...        C19H22FN3O   
1   3-{[1,1'-biphenyl]-4-ylmethylidene}-6-fluoro-2...        C22H15FO3S   
2   1-{[3-(4-methoxyphenyl)-1,2,4-oxadiazol-5-yl]m...        C25H28N4O3   
3   3-[2-oxo-2-(4-phenylmethanesulfonylpiperazin-1...       C22H30N4O5S   
4   2-{[1,1'-biphenyl]-2-ylamino}-1-(morpholin-4-y...        C18H20N2O2   
5   1-(2-{[1,1'-biphenyl]-2-ylamino}acetyl)imidazo...        C17H17N3O2   
6   N-(2,3-dihydro-1,4-benzodioxin-6-yl)-2-{[1-(4-...      C23H21N5O3S2   
7                                              Tm_322                     
8   N-[(1-benzyl-3,5-dimethylpyrazol-4-yl)methyl]-...       C24H25N5O2S   
9   N-{[1,1'-biphenyl]-4-yl}-2-(2-oxoquinoxalin-1-...        C22H17N3O2   
10                                             Tm_322                     
11  N-(4-ethoxyphenyl)-2-{2-[5-(4-methylphenyl)-1,...        C25H24N6O3   
12                       

In [3]:
print(data.iloc[:, [10,13]])

   Adduct  Dimer.1
0   [M+H]  Monomer
1   [M+H]  Monomer
2   [M+H]  Monomer
3   [M+H]  Monomer
4   [M+H]  Monomer
5   [M+H]  Monomer
6   [M+H]  Monomer
7   [M+H]  Monomer
8   [M+H]  Monomer
9   [M+H]  Monomer
10  [M+H]  Monomer
11  [M+H]  Monomer
12  [M+H]  Monomer
13  [M+H]    Dimer
14  [M+H]  Monomer
15  [M+H]  Monomer
16  [M+H]  Monomer
17  [M+H]  Monomer
18  [M+H]  Monomer
19  [M+H]  Monomer
20  [M+H]    Dimer
21  [M+H]  Monomer
22  [M+H]  Monomer
23  [M+H]  Monomer
24  [M+H]  Monomer
25  [M+H]  Monomer
26  [M+H]  Monomer
27  [M+H]  Monomer
28  [M+H]  Monomer
29  [M+H]  Monomer
30  [M+H]  Monomer
31  [M+H]  Monomer
32  [M+H]  Monomer
33  [M+H]  Monomer
34  [M+H]  Monomer
35  [M+H]  Monomer
36  [M+H]  Monomer
37  [M+H]  Monomer
38  [M+H]  Monomer
39  [M+H]  Monomer
40  [M+H]  Monomer
41  [M+H]  Monomer
42  [M+H]  Monomer
43  [M+H]  Monomer
44  [M+H]  Monomer
45  [M+H]  Monomer
46  [M+H]  Monomer
47  [M+H]  Monomer
48  [M+H]  Monomer
49  [M+H]  Monomer


In [4]:
inputs, target = data.iloc[:, [9, 10, 13, 18]], data.iloc[:, 7]
print(inputs, target)

         m/z Adduct  Dimer.1  \
0   328.1820  [M+H]  Monomer   
1   379.0799  [M+H]  Monomer   
2   433.2234  [M+H]  Monomer   
3   463.2010  [M+H]  Monomer   
4   297.1598  [M+H]  Monomer   
5   296.1394  [M+H]  Monomer   
6   480.1159  [M+H]  Monomer   
7   322.0481  [M+H]  Monomer   
8   448.1802  [M+H]  Monomer   
9   356.1394  [M+H]  Monomer   
10  322.0481  [M+H]  Monomer   
11  457.1983  [M+H]  Monomer   
12  622.0290  [M+H]  Monomer   
13  331.1441  [M+H]    Dimer   
14  415.1720  [M+H]  Monomer   
15  527.1595  [M+H]  Monomer   
16  392.1063  [M+H]  Monomer   
17  509.1676  [M+H]  Monomer   
18  311.1754  [M+H]  Monomer   
19  363.2067  [M+H]  Monomer   
20  362.0612  [M+H]    Dimer   
21  214.0863  [M+H]  Monomer   
22  578.1526  [M+H]  Monomer   
23  496.1813  [M+H]  Monomer   
24  450.0031  [M+H]  Monomer   
25  459.1308  [M+H]  Monomer   
26  424.0213  [M+H]  Monomer   
27  405.0904  [M+H]  Monomer   
28  410.0815  [M+H]  Monomer   
29  490.2159  [M+H]  Monomer   
30  366.

In [5]:
import torch 

mz = torch.tensor(data.iloc[:, 9].to_numpy(dtype=float))
print(mz)

tensor([328.1820, 379.0799, 433.2234, 463.2010, 297.1598, 296.1394, 480.1159,
        322.0481, 448.1802, 356.1394, 322.0481, 457.1983, 622.0290, 331.1441,
        415.1720, 527.1595, 392.1063, 509.1676, 311.1754, 363.2067, 362.0612,
        214.0863, 578.1526, 496.1813, 450.0031, 459.1308, 424.0213, 405.0904,
        410.0815, 490.2159, 366.0941, 431.2078, 322.0481, 442.1595, 481.1210,
        463.1089, 483.2061, 476.2002, 413.1496, 345.0459, 446.1645, 416.1605,
        468.2493, 404.1969, 454.1254, 484.0551, 489.0453, 469.0369, 922.0098,
        385.1944], dtype=torch.float64)


In [6]:
for k, adduct in enumerate(data.iloc[:, 10]):
    # Check if the adduct is [M+H] (=1) or other (=0)
    if adduct == '[M+H]':
        data.iloc[k, 10] = 1
    else:
        data.iloc[k, 10] = 0
        
adduct = torch.tensor(data.iloc[:, 10].to_numpy(dtype=float))
print(adduct)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       dtype=torch.float64)


In [7]:
for i, dimer in enumerate(data.iloc[:, 13]):
    # Check if the chemical is 'monomer' or 'dimer' and assign 1 or 0 accordingly
    if dimer == 'Monomer':
        data.iloc[i, 13] = 1
    elif dimer == 'Dimer':
        data.iloc[i, 13] = 0

dimer = torch.tensor(data.iloc[:, 13].to_numpy(dtype=float))
print(dimer)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
        1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       dtype=torch.float64)


In [8]:
import torch
from torch.nn.utils.rnn import pad_sequence
import numpy as np

print(data.iloc[:, 18])

# Function to tokenize an InChI string
def tokenize_inchi(inchi_string):
    return list(inchi_string)

# Function to map tokens to integer indices
def map_tokens_to_indices(tokens, token_to_index):
    return [token_to_index[token] for token in tokens if token in token_to_index]

inchis = []
for j, inchi in enumerate(data.iloc[:, 18]):
    inchi_string = data.iloc[j, 18]
    tokens = tokenize_inchi(inchi_string)
    vocabulary = list(set(tokens))
    token_to_index = {token: j for j, token in enumerate(vocabulary)}
    indices = map_tokens_to_indices(tokens, token_to_index)
    print(indices)
    inchi_tensor = torch.tensor(indices)
    inchis.append(inchi_tensor)

#print(inchis)

inchis_matrix = pad_sequence(inchis, batch_first=True, padding_value=0)
#print(padded_inchis)
#inchis_matrix = padded_inchis.t() # traspuesta para tener un inchi (vector) por columna 
#print(inchis_matrix)
#print('number of columns:', inchis_matrix.size(1))

0     InChI=1S/C19H22FN3O/c20-17-8-6-15(7-9-17)14-22...
1     InChI=1S/C22H15FO3S/c23-19-10-11-21-20(13-19)2...
2     InChI=1S/C25H28N4O3/c1-31-21-10-8-19(9-11-21)2...
3     InChI=1S/C22H30N4O5S/c27-19(16-26-20(28)22(23-...
4     InChI=1S/C18H20N2O2/c21-18(20-10-12-22-13-11-2...
5     InChI=1S/C17H17N3O2/c21-16(20-11-10-18-17(20)2...
6     InChI=1S/C23H21N5O3S2/c1-16-4-6-17(7-5-16)28-2...
7                                                    --
8     InChI=1S/C24H25N5O2S/c1-16-12-20(28-31-16)15-3...
9     InChI=1S/C22H17N3O2/c26-21(15-25-20-9-5-4-8-19...
10                                                   --
11    InChI=1S/C25H24N6O3/c1-3-34-20-14-12-19(13-15-...
12                                                   --
13    InChI=1S/C21H18N2O2/c22-21(25)18-8-4-5-9-19(18...
14    InChI=1S/C19H30N2O4S2/c1-2-21(17-9-5-3-6-10-17...
15    InChI=1S/C25H28N4O7S/c1-2-28(22-23(26)29(25(33...
16    InChI=1S/C21H17N3O3S/c1-2-5-15(6-3-1)12-24-20(...
17    InChI=1S/C26H28N4O3S2/c31-24(18-20-13-14-2

In [9]:
print(torch.tensor(inchis_matrix))

tensor([[13,  9, 20,  ...,  0,  0,  0],
        [12,  8, 19,  ...,  0,  0,  0],
        [12,  8, 19,  ...,  0,  0,  0],
        ...,
        [13,  9, 22,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [12,  8, 19,  ...,  0,  0,  0]])


C:\Users\carlo\AppData\Local\Temp\ipykernel_19960\22522981.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(torch.tensor(inchis_matrix))


In [13]:
from torch.utils.data import TensorDataset, DataLoader

data_matrix = []

for i in range(len(data)): # the four tensor vectors (mz, dimer, adduct, target) have the same lengths 
    # Select the corresponding values from each tensor vector
    new_row = [mz[i], dimer[i], adduct[i], target[i], inchis_matrix[i, :]]
    data_matrix.append(new_row)


dataframe = pd.DataFrame(data_matrix, columns=['mz', 'dimer', 'adduct', 'target', 'inchis'])

print(dataframe)


# Convert the list of tuples into a dataset


datasi = d2l.DataModule(dataframe)
#dataloader = DataLoader(dataframe, batch_size=batch_size, shuffle=True)

                                       mz                            dimer  \
0   tensor(328.1820, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
1   tensor(379.0799, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
2   tensor(433.2234, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
3   tensor(463.2010, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
4   tensor(297.1598, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
5   tensor(296.1394, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
6   tensor(480.1159, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
7   tensor(322.0481, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
8   tensor(448.1802, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
9   tensor(356.1394, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
10  tensor(322.0481, dtype=torch.float64)  tensor(1., dtype=torch.float64)   
11  tensor(457.1983, dtype=torch.float64)  tensor(1., dtype=torc

3

In [14]:
import numpy as np
import torch
from torch import nn
from d2l import torch as d2l

class MLP(d2l.Classifier):
    def __init__(self, num_outputs, num_hiddens, lr):
        super().__init__()
        self.save_hyperparameters()
        self.net = nn.Sequential(nn.Flatten(), nn.LazyLinear(num_hiddens),
                                 nn.ReLU(), nn.LazyLinear(num_outputs))

model = MLP(num_outputs=10, num_hiddens=256, lr=0.1)
trainer = d2l.Trainer(max_epochs=10)
trainer.fit(model, datasi)

C:\Users\carlo\anaconda3\Lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


NotImplementedError: 

In [ ]:
@d2l.add_to_class(LinearRegression)  #@save
def get_w_b(self):
    return (self.net.weight.data, self.net.bias.data)
w, b = model.get_w_b()

print(f'error in estimating w: {data.w - w.reshape(data.w.shape)}')
print(f'error in estimating b: {data.b - b}')

In [32]:
import subprocess

# Define the directory where your repository is located
repo_dir = 'tfg_ccsPrediction'

# Change directory to the repository directory
subprocess.run(['cd', repo_dir], shell=True)

# Add all changes to the staging area
subprocess.run(['git', 'add', '.'])

# Commit changes with a commit message
commit_message = "Your commit message here"
subprocess.run(['git', 'commit', '-m', commit_message])

# Push changes to the remote repository (origin)
subprocess.run(['git', 'push', 'origin', 'main'])  # Replace 'main' with your branch name if necessary


CompletedProcess(args=['git', 'push', 'origin', 'main'], returncode=128)